### ISSUE TITLE
Registration and User Accounts

### ISSUE THREAD

**Issue by DavidFB94** [DavidFB94/pro-fit-pt#1]
## Acceptance Criteria:
- [x] AC 1: Account registration - #2 
- [x] AC 2: Registration confirmation - #29
- [x] AC 3: Account login - #3 
- [x] AC 4: Account logout - #4
- [x] AC 5: User profile - #10
- [x] AC 6: Save delivery information - #9
- [x] AC 7: View order history - #8
