### ISSUE TITLE
User profile

### ISSUE THREAD

**Issue by DavidFB94** [DavidFB94/pro-fit-pt#14]
## Acceptance Criteria:
- [ ] AC 1: Access user profile - #10
- [ ] AC 2: Save delivery information - #9 
- [ ] AC 3: View order history - #8
