### ISSUE TITLE
Customer contact

### ISSUE THREAD

**Issue by DavidFB94** [DavidFB94/pro-fit-pt#19]
## Acceptance Criteria:
- [x] AC 1: Send contact form - #16 
- [x] AC 2: Receive contact forms - #17 
- [x] AC 3: Mark contact messages as "read" - #18
